//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inputs
    {
        public int id { get; set; }
        public string Level { get; set; }
        public string Lang { get; set; }
        public string Tweets { get; set; }
        public string PhD { get; set; }
        public string Result { get; set; }
    }
}
